### ISSUE TITLE
SCSS file not found

### ISSUE THREAD

**Issue by agentlewis** [raisely/cli#30]
Hey team, I just setup a new repo following the quickstart guides and using 2 worflows to deploy a staging and production environment.

Unfortunately this is the error I am bumping up into 

![image](https://user-images.githubusercontent.com/1431991/178314739-4e4d40c6-feb8-41ee-a384-094ae589035d.png)

This may be similar to #24 ?

To clarify, there are currently no .scss files in the stylesheet folder. I just ran `raisely update` and thats whats there. 

NOTE: I am also using github envirnoments to store the secrets for each of the deployments.

Oh our repo is public so you can see it here: https://github.com/bamboocreativenz/livingsober-raisely

Any help would be much appreciated.

**Comment by agentlewis** [comment]
Folllow up context:

My two worflows are producing different areas - which is really weird. I have checked the secrets and uuids multiple times

![image](https://user-images.githubusercontent.com/1431991/178318135-88b581e3-63a6-4cc3-a413-ddef76e2124a.png)

**Comment by agentlewis** [comment]
Sorry one more update:

So I created a folder/file in the staging branch `living-sober-dev/living-sober-dev.scss` and its now got me past that error. This is still concerning as it means the path is not deployment agnostic.

But at least now its just the same error as the main branch which is that it can't get the environment variable from the repo.

![image](https://user-images.githubusercontent.com/1431991/178324674-5d4e45f1-874b-4786-b30f-5757b6609e05.png)

**Comment by agentlewis** [comment]
ok last update:

I tried moving all my secrets into normal repo secrots - no dice. So at this point I suspect this action is misconfigured somehow.

![image](https://user-images.githubusercontent.com/1431991/178328789-cfc75f62-1fc7-497f-87e2-211ebb42b313.png)

**Comment by tommaitland** [comment]
@agentlewis If you read my reply to #35 first you might get more context, but currently the folder name and base file name are meaningful in the CLI. I know this makes it tricky to do a staging -> production workflow and that's one of the big areas of our developer experience we'd like to improve.

I suspect here that your production campaign is called `living-sober` and your dev campaign is `living-sober-dev`. From what I can see from your screenshots, the CLI is unhappy that you're trying to deploy to an account where `living-sober-dev` doesn't exist because it's your production account.

I don't think we have a good way around this right now, so my only suggestion would be to rename the folder and the base style before running `raisely deploy` in the Github Action.

If you like, happy to hop on a call and troubleshoot this with you and explain a little more about how CLI works and how we generally work with it – might give you context for the other things you've raised.

Just email me – tom@raisely.com

**Comment by agentlewis** [comment]
Sweet as @tommaitland ill email you in the morning. I need to get some shut eye.

I think I get what your saying regarding folder naming, but I’ll need to level up a little on my action-fu to make it work.

**Comment by agentlewis** [comment]
@tommaitland thanks again for helping me out.

I have the setup working and just wanted to jot down some things here for anyone else that finds this issue.

Here are my updated envirorment variables:

![image](https://user-images.githubusercontent.com/1431991/178963822-24ad4ae9-1f70-4665-9aa8-4c103da5c13a.png)

Here is a dump of my action:

```YML
on:
  push:
    branches:
      - main
name: Raisely Deploy Staging
env:
  CAMPAIGN_NAME: ${{ secrets.RAISELY_CAMPAIGN_NAME }}
jobs:
  raiselyDeploy:
    name: Raisely Deploy
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://living-sober.raisely.com/
    steps:
    - uses: actions/checkout@v2
    - name: Create folder 
      run: mkdir stylesheets
    - name: Move and Rename styles folder 
      run: mv campaign-styles stylesheets/$CAMPAIGN_NAME 
    - name: Rename file 
      run:  mv stylesheets/$CAMPAIGN_NAME/custom-styles.scss stylesheets/$CAMPAIGN_NAME/$CAMPAIGN_NAME.scss
    - name: Raisely Deploy
      uses: raisely/deploy@v1
      with:
        campaign: ${{ secrets.RAISELY_CAMPAIGN_UUID }}
        apikey: ${{ secrets.RAISELY_API_KEY }}
```

Some things I have noticed:

 - This setup should ideally be used with the raisely `use local development` turned on
 - Running `raisely update` wont't play nice as the action will delete whatever is in the `stylesheets` folder (or maybe it will fail as it can't create a new `stylesheets` folder).
 
 Thanks for the help - appreciated the meandering chats as well. If I find someone that I think would be a good fit for you ill send them your way.
